services:
  - type: web
    name: jobika-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: jobika-db
          property: connectionString
  
  - type: pserv
    name: jobika-db
    env: postgres
    plan: free
    ipAllowList: []
